-- =============================================================================
-- Online Course — bulk seed (PostgreSQL 14+)
-- Schema fully verified from real DDL output (Apr 2026).
--
-- Real table / column corrections applied:
--   • app_users:      `status`        → `user_status`
--   • courses:        `instructor_id` → `user_id`
--                     no instructor ALTER needed (column already exists)
--   • course_groups:  real name of the groups table (NOT `groups`)
--   • group_members / group_courses: reference course_groups, no PK constraint
--   • enrollments:    status values → JOINED | LISTED | COMPLETED | ARCHIVED
--                     no UNIQUE(user_id,course_id) — use DISTINCT in INSERT
--   • lesson_progress / password_reset_*: left untouched (seed doesn't insert there)
--
-- Password for ALL seeded users: admin123
--   hash: $2a$12$MCY9lixPypUDNJi.2htnPe/BGMZSCTLAeUbjCDv.EjMJX5WVmpzPy
-- =============================================================================

ROLLBACK;
BEGIN;

-- ===========================================================================
-- 1. DDL  (CREATE IF NOT EXISTS — skipped safely when table already exists)
-- ===========================================================================

CREATE TABLE IF NOT EXISTS public.app_users (
  user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMP(6),
  updated_at  TIMESTAMP(6),
  email       VARCHAR(255) NOT NULL UNIQUE,
  full_name   VARCHAR(255),
  password    VARCHAR(255),
  user_info   JSONB,
  user_status VARCHAR(255) CHECK (user_status IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE IF NOT EXISTS public.app_user_roles (
  user_id BIGINT      NOT NULL REFERENCES public.app_users (user_id),
  role    VARCHAR(255)     CHECK (role IN ('ADMIN','TEACHER','STUDENT'))
);

CREATE TABLE IF NOT EXISTS public.categories (
  category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMP(6),
  updated_at    TIMESTAMP(6),
  category_name VARCHAR(255)
);

-- Real groups table is course_groups
CREATE TABLE IF NOT EXISTS public.course_groups (
  group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP(6),
  updated_at TIMESTAMP(6),
  group_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.courses (
  course_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMP(6),
  updated_at    TIMESTAMP(6),
  course_img    VARCHAR(255),
  course_name   VARCHAR(255),
  course_status VARCHAR(255) CHECK (course_status IN ('NEW','POPULAR','RECOMMENDED')),
  description   VARCHAR(255),
  is_active     BOOLEAN,
  category_id   BIGINT REFERENCES public.categories  (category_id),
  user_id       BIGINT REFERENCES public.app_users   (user_id)
);

CREATE TABLE IF NOT EXISTS public.modules (
  module_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMP(6),
  updated_at   TIMESTAMP(6),
  module_title VARCHAR(255),
  position     INTEGER,
  course_id    BIGINT REFERENCES public.courses (course_id)
);

CREATE TABLE IF NOT EXISTS public.lessons (
  lesson_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   TIMESTAMP(6),
  updated_at   TIMESTAMP(6),
  content_text VARCHAR(255),
  duration     DOUBLE PRECISION NOT NULL DEFAULT 0,
  position     INTEGER          NOT NULL DEFAULT 0,
  title        VARCHAR(255),
  video_url    VARCHAR(255),
  module_id    BIGINT REFERENCES public.modules (module_id)
);

CREATE TABLE IF NOT EXISTS public.group_members (
  group_id BIGINT REFERENCES public.course_groups (group_id),
  user_id  BIGINT REFERENCES public.app_users     (user_id)
);

CREATE TABLE IF NOT EXISTS public.group_courses (
  group_id  BIGINT REFERENCES public.course_groups (group_id),
  course_id BIGINT REFERENCES public.courses       (course_id)
);

CREATE TABLE IF NOT EXISTS public.enrollments (
  enrollment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        TIMESTAMP(6),
  updated_at        TIMESTAMP(6),
  enrollment_date   TIMESTAMP(6),
  enrollment_status VARCHAR(255) CHECK (enrollment_status IN ('JOINED','LISTED','COMPLETED','ARCHIVED')),
  join_count        BIGINT,
  notes             VARCHAR(255),
  view_count        BIGINT,
  user_id           BIGINT REFERENCES public.app_users (user_id),
  course_id         BIGINT REFERENCES public.courses   (course_id)
);

-- ===========================================================================
-- 2. Indexes (only when column exists)
-- ===========================================================================

DO $idx$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='courses'     AND column_name='category_id')  THEN CREATE INDEX IF NOT EXISTS idx_courses_category   ON public.courses     (category_id);  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='courses'     AND column_name='user_id')       THEN CREATE INDEX IF NOT EXISTS idx_courses_user       ON public.courses     (user_id);       END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='modules'     AND column_name='course_id')     THEN CREATE INDEX IF NOT EXISTS idx_modules_course     ON public.modules     (course_id);     END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='lessons'     AND column_name='module_id')     THEN CREATE INDEX IF NOT EXISTS idx_lessons_module     ON public.lessons     (module_id);     END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='enrollments' AND column_name='user_id')       THEN CREATE INDEX IF NOT EXISTS idx_enrollments_user   ON public.enrollments (user_id);       END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='enrollments' AND column_name='course_id')     THEN CREATE INDEX IF NOT EXISTS idx_enrollments_course ON public.enrollments (course_id);     END IF;
END
$idx$;

-- ===========================================================================
-- 3. Wipe previous seed data
--    CASCADE handles lesson_progress and any other child tables automatically.
-- ===========================================================================

TRUNCATE
  public.lesson_progress,
  public.lessons,
  public.modules,
  public.group_courses,
  public.group_members,
  public.enrollments,
  public.courses,
  public.course_groups,
  public.app_user_roles,
  public.app_users,
  public.categories
RESTART IDENTITY CASCADE;

-- ===========================================================================
-- 4. Seed data
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- app_users (500)  — user_status confirmed column name
-- ---------------------------------------------------------------------------
INSERT INTO public.app_users (email, full_name, password, user_status, created_at)
SELECT
  'seed.user.' || g || '@example.test',
  'Seed User ' || LPAD(g::text, 4, '0'),
  '$2a$12$MCY9lixPypUDNJi.2htnPe/BGMZSCTLAeUbjCDv.EjMJX5WVmpzPy',
  CASE WHEN g % 17 = 0 THEN 'INACTIVE' ELSE 'ACTIVE' END,
  now() - ((500 - g) * interval '1 hour')
FROM generate_series(1, 500) AS g;

-- Users 1–5: ADMIN + TEACHER  |  6–60: TEACHER  |  61–500: STUDENT
INSERT INTO public.app_user_roles (user_id, role) SELECT g, 'ADMIN'   FROM generate_series(1,   5) AS g;
INSERT INTO public.app_user_roles (user_id, role) SELECT g, 'TEACHER' FROM generate_series(1,  60) AS g;
INSERT INTO public.app_user_roles (user_id, role) SELECT g, 'STUDENT' FROM generate_series(61,500) AS g;

-- ---------------------------------------------------------------------------
-- Categories (48)
-- ---------------------------------------------------------------------------
INSERT INTO public.categories (category_name, created_at)
SELECT
  'Category ' || LPAD(g::text, 2, '0') || ' — ' ||
  (ARRAY['STEM','Arts','Business','Language','Health','Data'])[1 + (g % 6)],
  now()
FROM generate_series(1, 48) AS g;

-- ---------------------------------------------------------------------------
-- Courses (800) — instructor stored as user_id on the courses row
-- ---------------------------------------------------------------------------
INSERT INTO public.courses (category_id, user_id, course_name, description, is_active, course_status, created_at)
SELECT
  1 + ((g - 1) % 48),
  1 + ((g - 1) % 60),
  'Course ' || LPAD(g::text, 4, '0') || ' — ' || (ARRAY['NEW','POPULAR','RECOMMENDED'])[1 + (g % 3)],
  left('Description for seeded course ' || g || ': ' || repeat('lorem ipsum ', 8), 250),
  (g % 11 <> 0),
  (ARRAY['NEW','POPULAR','RECOMMENDED'])[1 + (g % 3)],
  now() - ((800 - g) * interval '2 hour')
FROM generate_series(1, 800) AS g;

-- ---------------------------------------------------------------------------
-- Modules (3,200 — 4 per course)
-- ---------------------------------------------------------------------------
INSERT INTO public.modules (course_id, module_title, position, created_at)
SELECT
  c.course_id,
  left('Module ' || m.pos || ' — Course ' || c.course_id, 250),
  m.pos,
  now()
FROM public.courses c
CROSS JOIN LATERAL generate_series(1, 4) AS m(pos);

-- ---------------------------------------------------------------------------
-- Lessons (16,000 — 5 per module)
-- ---------------------------------------------------------------------------
INSERT INTO public.lessons (module_id, title, video_url, content_text, duration, position, created_at)
SELECT
  mo.module_id,
  left('Lesson ' || lp.pos || ' — Module ' || mo.module_id, 250),
  'https://cdn.example.test/videos/' || mo.module_id || '/' || lp.pos || '.mp4',
  left('Lesson body for module ' || mo.module_id || ', lesson ' || lp.pos || '.', 250),
  (5 + (mo.module_id % 40) + lp.pos * 3)::double precision,
  lp.pos,
  now()
FROM public.modules mo
CROSS JOIN LATERAL generate_series(1, 5) AS lp(pos);

-- ---------------------------------------------------------------------------
-- course_groups (150) — real table name confirmed
-- ---------------------------------------------------------------------------
INSERT INTO public.course_groups (group_name, created_at)
SELECT 'Learning Group ' || LPAD(g::text, 3, '0'), now()
FROM generate_series(1, 150) AS g;

-- ~25 members per group from the student pool (users 61–500)
-- DISTINCT prevents duplicates since there's no PK on group_members
INSERT INTO public.group_members (group_id, user_id)
SELECT DISTINCT
  gi.gid,
  61 + ((gi.gid * 31 + mm.n * 7) % 440)
FROM generate_series(1, 150) AS gi(gid)
CROSS JOIN LATERAL generate_series(0, 24) AS mm(n);

-- 16 courses per group
INSERT INTO public.group_courses (group_id, course_id)
SELECT DISTINCT
  gi.gid,
  1 + ((gi.gid * 17 + kk.n * 13) % 800)
FROM generate_series(1, 150) AS gi(gid)
CROSS JOIN LATERAL generate_series(0, 15) AS kk(n);

-- ---------------------------------------------------------------------------
-- Enrollments (~19,800 rows — 45 courses per student, DISTINCT for safety)
-- enrollment_status values confirmed: JOINED | LISTED | COMPLETED | ARCHIVED
-- ---------------------------------------------------------------------------
INSERT INTO public.enrollments
  (user_id, course_id, enrollment_status, view_count, join_count, enrollment_date, created_at)
SELECT DISTINCT ON (su.uid, 1 + ((su.uid * 19 + ce.n * 23) % 800))
  su.uid,
  1 + ((su.uid * 19 + ce.n * 23) % 800),
  (ARRAY['JOINED','LISTED','COMPLETED','ARCHIVED'])[1 + ((su.uid + ce.n) % 4)],
  ((su.uid * 13 + ce.n * 3) % 200)::bigint,
  ((su.uid * 7  + ce.n * 11) % 80)::bigint,
  now() - ((ce.n * 3) * interval '1 day'),
  now()
FROM generate_series(61, 500) AS su(uid)
CROSS JOIN LATERAL generate_series(1, 45) AS ce(n);

COMMIT;

-- ===========================================================================
-- Sanity checks — run manually after seed
-- ===========================================================================
-- SELECT 'app_users'    , count(*) FROM public.app_users
-- UNION ALL SELECT 'categories'   , count(*) FROM public.categories
-- UNION ALL SELECT 'courses'      , count(*) FROM public.courses
-- UNION ALL SELECT 'modules'      , count(*) FROM public.modules
-- UNION ALL SELECT 'lessons'      , count(*) FROM public.lessons
-- UNION ALL SELECT 'course_groups', count(*) FROM public.course_groups
-- UNION ALL SELECT 'group_members', count(*) FROM public.group_members
-- UNION ALL SELECT 'group_courses', count(*) FROM public.group_courses
-- UNION ALL SELECT 'enrollments'  , count(*) FROM public.enrollments
-- ORDER BY 1;
